version: '3.7'
services:
  wordpress:
    image: wordpress
    networks:
      - setname
    depends_on:
      - db
    environment:
      WORDPRESS_DB_PASSWORD: test123
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_HOST: db:3306
      SERVICE_PORTS: 80
    deploy: 
      replicas: set_replicas
      placement: 
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
        max_attempts: 2

  db:
    image: mysql:5.7
    networks:
      - setname
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: testdb
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 2

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - wordpress
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: # attach on ingress network 1
      - 80
    networks: # attach on web network 2 - nginx connect
      - setname
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 2


networks:
  setname:
    external: true
volumes:
  dbvol:
